### PR TITLE
Added Git Initialisation Hooks

### PR DESCRIPTION
**Pull request by santacodes**
+ Added `git` initialisation hooks in the template to automatically initialise a `git repository` when a `generated project` is created by `cookiecutter`.
+ Added a default `main` branch parameter for git repository initialisation.

Subtask - #26

### CODE REVIEW

**Review by Saransh-cpp — APPROVED** [review]
Looks good, thanks @santacodes! I haven't tested this locally but could you confirm if this is working locally?

**Review by agriyakhetarpal — APPROVED** [review]
Thanks, @santacodes! While I shall approve this PR now so that it gets your other PR going, I would suggest that we provide an option in the template to not require `hatch-vcs` by default. Making this it an opt-in piece of functionality would be great, this way, this script would not be needed for installing the package. Moreover, I feel that new users of PyBaMM and newcomers to Python packaging would like to hardcode the package version in a string instead of trying to wrap their heads around version control systems.

**Comment by santacodes** [comment]
> Looks good, thanks @santacodes! I haven't tested this locally but could you confirm if this is working locally?

Yes it does, I tested it locally before pushing it.

**Comment by arjxn-py** [comment]
I'm also testing it quick locally

**Comment by santacodes** [comment]
> Thanks, @santacodes! While I shall approve this PR now so that it gets your other PR going, I would suggest that we provide an option in the template to not require `hatch-vcs` by default. Making this it an opt-in piece of functionality would be great, this way, this script would not be needed for installing the package. Moreover, I feel that new users of PyBaMM and newcomers to Python packaging would like to hardcode the package version in a string instead of trying to wrap their heads around version control systems.

I completely agree, I will add a new prompt for that to opt-in `hatch-vcs` and make it `false` by default so that they don't have to go through that hassle. Perhaps as you said the versions could be hardcoded in the `_version.py` file and can be configured through `tool.hatch.version`. I am working on the patch and will push that commit in #29, it should possibly resolve all the failing tests as well. Thank you for the insights!

**Review by arjxn-py — APPROVED** [review]
Works well, I'd now need to re-configure my git name & mail 😆

**Pull request merged**
